language: ruby
dist: trusty
sudo: false # explicitly use container-based architecture

branches:
  only:
    - master

cache: bundler
bundler_args: --without development # --path=~/.bundle

before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc" # skip installing docs for gems

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - "psql -c 'create database dogtag_test;' -U postgres"
  - "bin/rake db:migrate RAILS_ENV=test"

after_success:
  - bundle exec codeclimate-test-reporter
