language: ruby

sudo: false

branches:
  only:
    - master

cache: bundler

bundler_args: '--without development'

before_install:
  - 'echo "gem: --no-ri --no-rdoc" > ~/.gemrc'

services:
  - postgresql

addons:
  postgresql: '9.4'

before_script:
  - psql -c 'create database dogtag_test;' -U postgres
  - bin/rake db:migrate RAILS_ENV=test
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - bundle exec codeclimate-test-reporter

deploy:
  provider: heroku
  app: dogtag-staging
  on: master
  api_key:
    secure: kNlxn+CZBCxoo816X6tXACkkpVHBaFbduOhW3CzenY3+NOmLXJnuHClWvIc4ZzQuAWsLWAG/wrRr0hhxtxyvyT4kU4vl6X9RsEDMKLT+W6tnoJcIUdymxYK4Iaz8bYkXHQw0iMg5N7NPiT9JXcWTPfVb1fKqfD82oln7r6arLGI=
  run:
    - 'sleep 30'
    - 'rake db:migrate'
