version: "3.4"

x-default: &default
  build: .
  depends_on:
    - redis
    - db
  networks:
    - web
  volumes:
    - bundle_cache:/bundle_cache
    - .:/app

services:
  web:
    <<: *default
    environment:
      - DATABASE_URL=postgres://postgres@db:5432
      - REDIS_URL=redis://redis:6379/0
        # read stripe secrets from local env (or .env file)
      - STRIPE_PUBLISHABLE_KEY="${STRIPE_PUBLISHABLE_KEY}"
      - STRIPE_SECRET_KEY="${STRIPE_SECRET_KEY}"
        # TODO: SMTP_HOST might not be needed here
      - SMTP_HOST=mailcatcher
    ports:
      - "3000:3000"

  worker:
    <<: *default
    environment:
      - DATABASE_URL=postgres://postgres@db:5432
      - REDIS_URL=redis://redis:6379/0
      - SMTP_HOST=mailcatcher
      - SMTP_PORT=1025
    command: bundle exec sidekiq -t 10 -C ./config/sidekiq.yml

  db:
    image: postgres:14.7-alpine
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - web
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      - ./docker/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh

  redis:
    image: redis:5-alpine
    command: redis-server --appendonly yes
    networks:
      - web
    ports:
      - "6379:6379"
    volumes:
      - redis_cache:/data

  mailcatcher:
    build:
      context: .
      dockerfile: docker/Dockerfile.mailcatcher
    networks:
      - web
    volumes:
      - bundle_cache:/bundle_cache
    ports:
      - "1025:1025"
      - "1080:1080"

networks:
  web:

volumes:
  bundle_cache:
  redis_cache:
  pgdata:
