# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a7ea777eb9e0ad3c7809e3edf2d072ecd3f54d5db4935d8d74b3fe57d7ec61df1d091948f639c9a1e6d404b7d3fc0e80fcbdc05a214e51f1ec2d64480c39b45

test:
  secret_key_base: c993ddec624cafd078cc7aeaf55df1814c67846beec99a30a1549f90451f00502de82633bcc3aead0c6360004e947b7f0426b591841d074358a65f590d4ea879

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
